name: Mirroring

on: [push, delete]

jobs:
  to_mstem_quda:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@github.com:MSTEM-QUDA/util.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.MIRROR_SSH_PRIVATE_KEY_UTIL }}
